### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by aboettger** [NoYzE1/cRPG#1]
How can I start the game?

```
% python game.py  
Traceback (most recent call last):
  File "game.py", line 165, in <module>
    class Start:
  File "game.py", line 166, in Start
    Game.start()
TypeError: unbound method start() must be called with Game instance as first argument (got nothing instead)
```

**Comment by NoYzE1** [comment]
Oh, it's written in Python3 so you'll have to enter: "Python3 game.py"
I should probably add a shebang to it.
